### ISSUE TITLE
Return file flag does not return the file

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#71]
Using the return file flag only creates the file and sends a URL for the file.  Perhaps, it should return the file in the response instead.

**Comment by 16zzundel5** [comment]
Fixed and uploaded to shang. Also updated the docs.

**Comment by cjmyers** [comment]
This has broke synbiohub.  I change return_file to false, and I’m getting back an error.  Shouldn’t I still get back the URI and be able to fetch it as we discussed?

**Comment by cjmyers** [comment]
Switching back to return_file true, seems to work.

**Comment by 16zzundel5** [comment]
Fixed.

**Comment by cjmyers** [comment]
It is working now.  I will though get it changed to remove the get request, since no longer needed with return_file true.  

Thanks,

Chris
